/**
 * StepCharge AI — telemetry contract.
 *
 * Provenance matters in this project. Every numeric field is tagged below as:
 *   MEASURED   — read from hardware (ADC on ESP32)
 *   CALCULATED — derived arithmetically from measured values
 *   ESTIMATED  — modelled, not directly measured (documented assumptions)
 *   PREDICTED  — ML model output (always paired with a confidence)
 *   SIMULATED  — generated by the demo data source (never from hardware)
 *
 * `null` is meaningful: it means "this prototype does not measure it".
 * Never substitute 0 or a synthetic value for null in LIVE mode.
 */

export type StepClass = 'LIGHT' | 'NORMAL' | 'HEAVY'
/** A step the system has not (yet) classified. Never silently coerced to NORMAL. */
export type StepLabel = StepClass | 'UNKNOWN'
export type DeviceStatus = 'online' | 'degraded' | 'offline'
export type Provenance = 'MEASURED' | 'CALCULATED' | 'ESTIMATED' | 'PREDICTED' | 'SIMULATED'
export type SourceMode = 'demo' | 'live'

/** Raw JSON exactly as the ESP32 publishes it (camelCase, nullable sensors). */
export interface Esp32Payload {
  deviceId: string
  timestamp: string
  footstepCount: number
  peakVoltage: number
  averageVoltage: number
  pulseDuration: number // ms
  stepInterval: number // seconds
  storageVoltage: number
  current: number | null // A — null when no current-sense hardware
  power: number | null // W — null unless current is measured
  energy: number | null // J — null unless integrated from measured power
  stepClass?: StepClass | null // optional on-device inference
  confidence?: number | null
  wifiRssi: number
  uptimeSec?: number
  deviceStatus: 'ONLINE' | 'DEGRADED' | 'OFFLINE'
  firmwareVersion?: string
  loadControlAvailable?: boolean
  /** Per-element diagnostics — only present if the mat is individually channelled. */
  piezoArray?: Array<{ id: string; voltage: number; status: string; activityCount?: number; lastActive?: string }>
}

/** Command/actual pair for one controllable load. */
export interface LoadState {
  command: boolean
  /** What the firmware reports the GPIO actually is. null = never reported back. */
  actualState: boolean | null
  updatedAt?: string
  reportedAt?: string
}

export type LoadKey = 'led' | 'fan'
export type LoadMap = Record<LoadKey, LoadState>

export const EMPTY_LOADS: LoadMap = {
  led: { command: false, actualState: null },
  fan: { command: false, actualState: null },
}

/** Device registration record (devices/{deviceId}). */
export interface DeviceInfo {
  deviceId: string
  name: string
  location: string
  firmwareVersion: string
  status: 'ONLINE' | 'DEGRADED' | 'OFFLINE'
  lastSeen: string | null
  /** Reported by firmware. null when the device does not publish it. */
  uptimeSec: number | null
  wifiRssi: number | null
}

/** Normalised internal packet consumed by the store and every component. */
export interface TelemetryPacket {
  timestamp: string // ISO-8601
  device_id: string
  footstep_count: number // MEASURED (counter)
  peak_voltage: number // MEASURED (V)
  average_voltage: number // MEASURED (V)
  storage_voltage: number // MEASURED (V)
  pulse_duration_ms: number // MEASURED
  step_interval_ms: number // MEASURED
  current_a: number | null // MEASURED or null when unavailable
  power_w: number | null // MEASURED·CALCULATED (V×I) or null
  measured_energy_j: number | null // CALCULATED (∫P dt) or null
  estimated_energy_j: number // ESTIMATED (½CV²) — always available
  step_class: StepLabel // PREDICTED, or UNKNOWN when nothing has classified it
  confidence: number | null // PREDICTED 0..1, null when unclassified
  probabilities: Record<StepClass, number> | null
  prediction_source: PredictionSource
  loads: LoadMap // command + actual GPIO state
  load_control_available: boolean // capability flag reported by firmware
  wifi_rssi: number // MEASURED (dBm)
  uptime_sec: number | null // DEVICE REPORTED, null if firmware omits it
  device_status: DeviceStatus
  firmware_version: string
  source: SourceMode
}

/** Where a classification came from — surfaced in the UI, never blurred. */
export type PredictionSource = 'DEMO PREDICTION' | 'ML PREDICTION' | 'DEVICE PREDICTION' | 'UNCLASSIFIED'

export interface StepFeatures {
  peakVoltage: number
  averageVoltage: number
  pulseDuration: number // ms
  stepInterval: number // s
  storageVoltage: number
}

export interface Prediction {
  class: StepClass
  confidence: number
  probabilities: Record<StepClass, number>
  source: PredictionSource
  /** Per-feature contribution, 0..1, only populated when the model supplies it. */
  contributions?: Record<keyof StepFeatures, number>
  modelVersion?: string
}

export interface FootstepEvent {
  id: string
  timestamp: string
  device_id: string
  features: StepFeatures
  step_class: StepLabel
  confidence: number | null
  prediction_source: PredictionSource
  /** denormalised for fast table/chart access */
  peak_voltage: number
  pulse_duration_ms: number
  step_interval_ms: number
  storage_voltage: number
  estimated_energy_j: number
  source: SourceMode
}

export type AlertSeverity = 'critical' | 'warning' | 'info' | 'success'
export type AlertCategory = 'HARDWARE' | 'NETWORK' | 'ENERGY' | 'AI' | 'SYSTEM'

export interface AlertItem {
  id: string
  timestamp: string
  severity: AlertSeverity
  category: AlertCategory
  title: string
  reason: string
  currentValue: string
  threshold: string
  action: string
  resolved?: boolean
  read?: boolean
}

export type AnomalyKind =
  | 'VOLTAGE_SPIKE'
  | 'VOLTAGE_DROP'
  | 'LONG_PULSE'
  | 'SHORT_PULSE'
  | 'ABNORMAL_INTERVAL'
  | 'MISSING_TELEMETRY'
  | 'COMMS_INTERRUPTION'
  | 'LOW_GENERATION'

export interface Anomaly {
  id: string
  timestamp: string
  kind: AnomalyKind
  label: string
  reason: string
  level: 'NORMAL' | 'WARNING' | 'CRITICAL'
  /** Rule-based detector score, not an ML probability. */
  score: number
  status: 'Needs Review' | 'Acknowledged' | 'Resolved'
  metric: string
}

export interface AiInsight {
  id: string
  type: 'ENERGY INSIGHT' | 'FOOTSTEP INSIGHT' | 'STORAGE INSIGHT' | 'ANOMALY INSIGHT'
  text: string
  confidence: number
  timestamp: string
  supporting: string
}

export interface SystemHealth {
  esp32: DeviceStatus
  wifi: 'connected' | 'disconnected'
  cloud: 'connected' | 'error' | 'not-configured'
  sensor: 'normal' | 'noisy' | 'fault' | 'unknown'
  storage: 'normal' | 'low' | 'over'
  mlService: 'online' | 'offline' | 'demo'
  dashboard: 'live' | 'stale'
  lastDataMs: number
  rssi: number
  /** DEVICE REPORTED. null when the firmware does not publish uptime. */
  uptimeSec: number | null
  lastReboot: string | null
  /** DASHBOARD CALCULATED from the packets this session has actually observed. */
  packetsReceived: number
  packetsMissed: number
  successRate: number
  latencyMs: number | null
  deviceId: string
  firmwareVersion: string
  healthScore: number
}

/** Piezo element diagnostics — only available if firmware reports per-element data. */
export interface PiezoSensor {
  id: string
  index: number
  state: 'healthy' | 'weak' | 'inactive' | 'fault'
  voltage: number
  activityCount: number
  lastActive: string
}

export interface ModelMetadata {
  /** How the metrics were obtained — decides whether they are defensible. */
  evaluationMethod?: string | null
  evaluationDetail?: string | null
  subjectIndependent?: boolean
  participants?: number
  randomSeed?: number
  featureNames?: string[]
  warnings?: string[]
  connected: boolean
  source: 'demo' | 'api'
  modelName: string
  version: string
  trainedAt: string | null
  featureCount: number
  datasetVersion: string | null
  classes: StepClass[]
  metrics: { accuracy: number; precision: number; recall: number; f1: number } | null
  /** rows = actual, cols = predicted, ordered LIGHT, NORMAL, HEAVY */
  confusionMatrix: number[][] | null
  featureImportance: Record<keyof StepFeatures, number> | null
  samples: { total: number; train: number; test: number } | null
  labelDistribution: Record<StepClass, number> | null
}

export interface DatasetSample {
  id: string
  timestamp: string
  features: StepFeatures
  /** Ground-truth label supplied by the operator during collection. */
  label: StepClass
  deviceId: string
  source: SourceMode
  /** Who produced this footstep. Enables subject-independent ML validation. */
  participantId?: string
  note?: string
}

export interface Settings {
  deviceId: string
  samplingIntervalMs: number
  txIntervalMs: number
  storageTargetV: number
  minOperatingV: number
  maxSafeV: number
  supercapFarads: number
  energyMode: 'auto' | 'estimate' | 'measured'
  modelName: string
  classificationThreshold: number
  confidenceThreshold: number
  enabledClasses: StepClass[]
  alertsEnabled: boolean
  lowStorageAlertV: number
  spikeAlertV: number
  offlineTimeoutSec: number
  /** Firmware detection parameters, mirrored here for documentation + alerting. */
  footstepThresholdV: number
  debounceMs: number
  /** Dashboard warns above this, mirroring WARNING_STORAGE_VOLTAGE in firmware. */
  warnStorageV: number
  deviceName: string
  deviceLocation: string
  theme: 'dark' | 'light'
  refreshRateMs: number
  units: 'SI' | 'mixed'
}

export type RangeKey = 'today' | 'yesterday' | '7d' | '30d' | 'custom'
export type ConnectionState = 'idle' | 'connecting' | 'connected' | 'error'

export interface HistoryQuery {
  range: RangeKey
  custom?: { from: string; to: string }
  /** Hard cap so a live database is never pulled down in full. */
  limit?: number
}

/** The single contract the UI depends on — demo and live both satisfy it. */
export interface DataSource {
  readonly mode: SourceMode
  readonly label: string
  connect(): Promise<void>
  disconnect(): void
  subscribeTelemetry(cb: (p: TelemetryPacket) => void): () => void
  subscribeEvents(cb: (e: FootstepEvent) => void): () => void
  queryHistory(q: HistoryQuery): Promise<FootstepEvent[]>
  getPiezoArray(): Promise<PiezoSensor[] | null>
  subscribeLoads(cb: (l: LoadMap) => void): () => void
  subscribeDevice(cb: (d: DeviceInfo | null) => void): () => void
  /** Writes the COMMAND only. actualState comes back from the firmware. */
  setLoad(load: LoadKey, on: boolean): Promise<void>
}
